FROM ubi8/ubi:8.3

MAINTAINER Yasser Sheriff <ysherif@us.ibm.com>

LABEL description="A custom container image based on ubi 8.3"

RUN yum install -y httpd && \
    yum clean all

RUN echo "Hello from containerfile" > /var/www/html/index.html

EXPOSE 80

CMD ["httpd", "-D", "FOREGROUND"]

